//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sjuklöner.BankIDService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bankid.com/RpService/v4.0.0/types/")]
    public partial class RpFaultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FaultStatusType faultStatusField;
        
        private string detailedDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public FaultStatusType faultStatus {
            get {
                return this.faultStatusField;
            }
            set {
                this.faultStatusField = value;
                this.RaisePropertyChanged("faultStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string detailedDescription {
            get {
                return this.detailedDescriptionField;
            }
            set {
                this.detailedDescriptionField = value;
                this.RaisePropertyChanged("detailedDescription");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bankid.com/RpService/v4.0.0/types/")]
    public enum FaultStatusType {
        
        /// <remarks/>
        INVALID_PARAMETERS,
        
        /// <remarks/>
        ACCESS_DENIED_RP,
        
        /// <remarks/>
        CLIENT_ERR,
        
        /// <remarks/>
        CERTIFICATE_ERR,
        
        /// <remarks/>
        RETRY,
        
        /// <remarks/>
        INTERNAL_ERROR,
        
        /// <remarks/>
        ALREADY_COLLECTED,
        
        /// <remarks/>
        EXPIRED_TRANSACTION,
        
        /// <remarks/>
        ALREADY_IN_PROGRESS,
        
        /// <remarks/>
        USER_CANCEL,
        
        /// <remarks/>
        CANCELLED,
        
        /// <remarks/>
        REQ_PRECOND,
        
        /// <remarks/>
        REQ_ERROR,
        
        /// <remarks/>
        REQ_BLOCKED,
        
        /// <remarks/>
        START_FAILED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bankid.com/RpService/v4.0.0/types/")]
    public partial class OrderResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string orderRefField;
        
        private string autoStartTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string orderRef {
            get {
                return this.orderRefField;
            }
            set {
                this.orderRefField = value;
                this.RaisePropertyChanged("orderRef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string autoStartToken {
            get {
                return this.autoStartTokenField;
            }
            set {
                this.autoStartTokenField = value;
                this.RaisePropertyChanged("autoStartToken");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bankid.com/RpService/v4.0.0/types/")]
    public partial class ConditionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string[] value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bankid.com/RpService/v4.0.0/types/")]
    public partial class RequirementType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ConditionType[] conditionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("condition", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ConditionType[] condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
                this.RaisePropertyChanged("condition");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bankid.com/RpService/v4.0.0/types/")]
    public partial class EndUserInfoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bankid.com/RpService/v4.0.0/types/")]
    public partial class AuthenticateRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string personalNumberField;
        
        private EndUserInfoType[] endUserInfoField;
        
        private RequirementType[] requirementAlternativesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string personalNumber {
            get {
                return this.personalNumberField;
            }
            set {
                this.personalNumberField = value;
                this.RaisePropertyChanged("personalNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("endUserInfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public EndUserInfoType[] endUserInfo {
            get {
                return this.endUserInfoField;
            }
            set {
                this.endUserInfoField = value;
                this.RaisePropertyChanged("endUserInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("requirement", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public RequirementType[] requirementAlternatives {
            get {
                return this.requirementAlternativesField;
            }
            set {
                this.requirementAlternativesField = value;
                this.RaisePropertyChanged("requirementAlternatives");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bankid.com/RpService/v4.0.0/", ConfigurationName="BankIDService.RpServicePortType")]
    public interface RpServicePortType {
        
        // CODEGEN: Generating message contract since the operation Authenticate is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sjuklöner.BankIDService.RpFaultType), Action="", Name="RpFault", Namespace="http://bankid.com/RpService/v4.0.0/types/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sjuklöner.BankIDService.AuthenticateResponse Authenticate(Sjuklöner.BankIDService.AuthenticateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Sjuklöner.BankIDService.AuthenticateResponse> AuthenticateAsync(Sjuklöner.BankIDService.AuthenticateRequest request);
        
        // CODEGEN: Generating message contract since the operation Sign is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sjuklöner.BankIDService.RpFaultType), Action="", Name="RpFault", Namespace="http://bankid.com/RpService/v4.0.0/types/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sjuklöner.BankIDService.SignResponse Sign(Sjuklöner.BankIDService.SignRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Sjuklöner.BankIDService.SignResponse> SignAsync(Sjuklöner.BankIDService.SignRequest request);
        
        // CODEGEN: Generating message contract since the operation FileSign is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sjuklöner.BankIDService.RpFaultType), Action="", Name="RpFault", Namespace="http://bankid.com/RpService/v4.0.0/types/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sjuklöner.BankIDService.FileSignResponse FileSign(Sjuklöner.BankIDService.FileSignRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Sjuklöner.BankIDService.FileSignResponse> FileSignAsync(Sjuklöner.BankIDService.FileSignRequest request);
        
        // CODEGEN: Generating message contract since the operation Collect is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sjuklöner.BankIDService.RpFaultType), Action="", Name="RpFault", Namespace="http://bankid.com/RpService/v4.0.0/types/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sjuklöner.BankIDService.CollectResponse Collect(Sjuklöner.BankIDService.CollectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Sjuklöner.BankIDService.CollectResponse> CollectAsync(Sjuklöner.BankIDService.CollectRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateRequest", Namespace="http://bankid.com/RpService/v4.0.0/types/", Order=0)]
        public Sjuklöner.BankIDService.AuthenticateRequestType AuthenticateRequest1;
        
        public AuthenticateRequest() {
        }
        
        public AuthenticateRequest(Sjuklöner.BankIDService.AuthenticateRequestType AuthenticateRequest1) {
            this.AuthenticateRequest1 = AuthenticateRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bankid.com/RpService/v4.0.0/types/", Order=0)]
        public Sjuklöner.BankIDService.OrderResponseType AuthResponse;
        
        public AuthenticateResponse() {
        }
        
        public AuthenticateResponse(Sjuklöner.BankIDService.OrderResponseType AuthResponse) {
            this.AuthResponse = AuthResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bankid.com/RpService/v4.0.0/types/")]
    public partial class SignRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string personalNumberField;
        
        private string userVisibleDataField;
        
        private string userNonVisibleDataField;
        
        private EndUserInfoType[] endUserInfoField;
        
        private RequirementType[] requirementAlternativesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string personalNumber {
            get {
                return this.personalNumberField;
            }
            set {
                this.personalNumberField = value;
                this.RaisePropertyChanged("personalNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string userVisibleData {
            get {
                return this.userVisibleDataField;
            }
            set {
                this.userVisibleDataField = value;
                this.RaisePropertyChanged("userVisibleData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string userNonVisibleData {
            get {
                return this.userNonVisibleDataField;
            }
            set {
                this.userNonVisibleDataField = value;
                this.RaisePropertyChanged("userNonVisibleData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("endUserInfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public EndUserInfoType[] endUserInfo {
            get {
                return this.endUserInfoField;
            }
            set {
                this.endUserInfoField = value;
                this.RaisePropertyChanged("endUserInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("requirement", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public RequirementType[] requirementAlternatives {
            get {
                return this.requirementAlternativesField;
            }
            set {
                this.requirementAlternativesField = value;
                this.RaisePropertyChanged("requirementAlternatives");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignRequest", Namespace="http://bankid.com/RpService/v4.0.0/types/", Order=0)]
        public Sjuklöner.BankIDService.SignRequestType SignRequest1;
        
        public SignRequest() {
        }
        
        public SignRequest(Sjuklöner.BankIDService.SignRequestType SignRequest1) {
            this.SignRequest1 = SignRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignResponse", Namespace="http://bankid.com/RpService/v4.0.0/types/", Order=0)]
        public Sjuklöner.BankIDService.OrderResponseType SignResponse1;
        
        public SignResponse() {
        }
        
        public SignResponse(Sjuklöner.BankIDService.OrderResponseType SignResponse1) {
            this.SignResponse1 = SignResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bankid.com/RpService/v4.0.0/types/")]
    public partial class FileSignRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string personalNumberField;
        
        private string userVisibleDataField;
        
        private string userNonVisibleDataField;
        
        private string fileNameField;
        
        private byte[] fileContentField;
        
        private EndUserInfoType[] endUserInfoField;
        
        private RequirementType[] requirementAlternativesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string personalNumber {
            get {
                return this.personalNumberField;
            }
            set {
                this.personalNumberField = value;
                this.RaisePropertyChanged("personalNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string userVisibleData {
            get {
                return this.userVisibleDataField;
            }
            set {
                this.userVisibleDataField = value;
                this.RaisePropertyChanged("userVisibleData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string userNonVisibleData {
            get {
                return this.userNonVisibleDataField;
            }
            set {
                this.userNonVisibleDataField = value;
                this.RaisePropertyChanged("userNonVisibleData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=4)]
        public byte[] fileContent {
            get {
                return this.fileContentField;
            }
            set {
                this.fileContentField = value;
                this.RaisePropertyChanged("fileContent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("endUserInfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public EndUserInfoType[] endUserInfo {
            get {
                return this.endUserInfoField;
            }
            set {
                this.endUserInfoField = value;
                this.RaisePropertyChanged("endUserInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("requirement", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public RequirementType[] requirementAlternatives {
            get {
                return this.requirementAlternativesField;
            }
            set {
                this.requirementAlternativesField = value;
                this.RaisePropertyChanged("requirementAlternatives");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FileSignRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FileSignRequest", Namespace="http://bankid.com/RpService/v4.0.0/types/", Order=0)]
        public Sjuklöner.BankIDService.FileSignRequestType FileSignRequest1;
        
        public FileSignRequest() {
        }
        
        public FileSignRequest(Sjuklöner.BankIDService.FileSignRequestType FileSignRequest1) {
            this.FileSignRequest1 = FileSignRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FileSignResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FileSignResponse", Namespace="http://bankid.com/RpService/v4.0.0/types/", Order=0)]
        public Sjuklöner.BankIDService.OrderResponseType FileSignResponse1;
        
        public FileSignResponse() {
        }
        
        public FileSignResponse(Sjuklöner.BankIDService.OrderResponseType FileSignResponse1) {
            this.FileSignResponse1 = FileSignResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bankid.com/RpService/v4.0.0/types/")]
    public partial class CollectResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ProgressStatusType progressStatusField;
        
        private string signatureField;
        
        private UserInfoType userInfoField;
        
        private string ocspResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ProgressStatusType progressStatus {
            get {
                return this.progressStatusField;
            }
            set {
                this.progressStatusField = value;
                this.RaisePropertyChanged("progressStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
                this.RaisePropertyChanged("signature");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public UserInfoType userInfo {
            get {
                return this.userInfoField;
            }
            set {
                this.userInfoField = value;
                this.RaisePropertyChanged("userInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ocspResponse {
            get {
                return this.ocspResponseField;
            }
            set {
                this.ocspResponseField = value;
                this.RaisePropertyChanged("ocspResponse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bankid.com/RpService/v4.0.0/types/")]
    public enum ProgressStatusType {
        
        /// <remarks/>
        OUTSTANDING_TRANSACTION,
        
        /// <remarks/>
        NO_CLIENT,
        
        /// <remarks/>
        STARTED,
        
        /// <remarks/>
        USER_SIGN,
        
        /// <remarks/>
        USER_REQ,
        
        /// <remarks/>
        COMPLETE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bankid.com/RpService/v4.0.0/types/")]
    public partial class UserInfoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string givenNameField;
        
        private string surnameField;
        
        private string nameField;
        
        private string personalNumberField;
        
        private System.DateTime notBeforeField;
        
        private System.DateTime notAfterField;
        
        private string ipAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string givenName {
            get {
                return this.givenNameField;
            }
            set {
                this.givenNameField = value;
                this.RaisePropertyChanged("givenName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
                this.RaisePropertyChanged("surname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string personalNumber {
            get {
                return this.personalNumberField;
            }
            set {
                this.personalNumberField = value;
                this.RaisePropertyChanged("personalNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime notBefore {
            get {
                return this.notBeforeField;
            }
            set {
                this.notBeforeField = value;
                this.RaisePropertyChanged("notBefore");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime notAfter {
            get {
                return this.notAfterField;
            }
            set {
                this.notAfterField = value;
                this.RaisePropertyChanged("notAfter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ipAddress {
            get {
                return this.ipAddressField;
            }
            set {
                this.ipAddressField = value;
                this.RaisePropertyChanged("ipAddress");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CollectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bankid.com/RpService/v4.0.0/types/", Order=0)]
        public string orderRef;
        
        public CollectRequest() {
        }
        
        public CollectRequest(string orderRef) {
            this.orderRef = orderRef;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CollectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CollectResponse", Namespace="http://bankid.com/RpService/v4.0.0/types/", Order=0)]
        public Sjuklöner.BankIDService.CollectResponseType CollectResponse1;
        
        public CollectResponse() {
        }
        
        public CollectResponse(Sjuklöner.BankIDService.CollectResponseType CollectResponse1) {
            this.CollectResponse1 = CollectResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RpServicePortTypeChannel : Sjuklöner.BankIDService.RpServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RpServicePortTypeClient : System.ServiceModel.ClientBase<Sjuklöner.BankIDService.RpServicePortType>, Sjuklöner.BankIDService.RpServicePortType {
        
        public RpServicePortTypeClient() {
        }
        
        public RpServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RpServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RpServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RpServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sjuklöner.BankIDService.AuthenticateResponse Sjuklöner.BankIDService.RpServicePortType.Authenticate(Sjuklöner.BankIDService.AuthenticateRequest request) {
            return base.Channel.Authenticate(request);
        }
        
        public Sjuklöner.BankIDService.OrderResponseType Authenticate(Sjuklöner.BankIDService.AuthenticateRequestType AuthenticateRequest1) {
            Sjuklöner.BankIDService.AuthenticateRequest inValue = new Sjuklöner.BankIDService.AuthenticateRequest();
            inValue.AuthenticateRequest1 = AuthenticateRequest1;
            Sjuklöner.BankIDService.AuthenticateResponse retVal = ((Sjuklöner.BankIDService.RpServicePortType)(this)).Authenticate(inValue);
            return retVal.AuthResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Sjuklöner.BankIDService.AuthenticateResponse> Sjuklöner.BankIDService.RpServicePortType.AuthenticateAsync(Sjuklöner.BankIDService.AuthenticateRequest request) {
            return base.Channel.AuthenticateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Sjuklöner.BankIDService.AuthenticateResponse> AuthenticateAsync(Sjuklöner.BankIDService.AuthenticateRequestType AuthenticateRequest1) {
            Sjuklöner.BankIDService.AuthenticateRequest inValue = new Sjuklöner.BankIDService.AuthenticateRequest();
            inValue.AuthenticateRequest1 = AuthenticateRequest1;
            return ((Sjuklöner.BankIDService.RpServicePortType)(this)).AuthenticateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sjuklöner.BankIDService.SignResponse Sjuklöner.BankIDService.RpServicePortType.Sign(Sjuklöner.BankIDService.SignRequest request) {
            return base.Channel.Sign(request);
        }
        
        public Sjuklöner.BankIDService.OrderResponseType Sign(Sjuklöner.BankIDService.SignRequestType SignRequest1) {
            Sjuklöner.BankIDService.SignRequest inValue = new Sjuklöner.BankIDService.SignRequest();
            inValue.SignRequest1 = SignRequest1;
            Sjuklöner.BankIDService.SignResponse retVal = ((Sjuklöner.BankIDService.RpServicePortType)(this)).Sign(inValue);
            return retVal.SignResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Sjuklöner.BankIDService.SignResponse> Sjuklöner.BankIDService.RpServicePortType.SignAsync(Sjuklöner.BankIDService.SignRequest request) {
            return base.Channel.SignAsync(request);
        }
        
        public System.Threading.Tasks.Task<Sjuklöner.BankIDService.SignResponse> SignAsync(Sjuklöner.BankIDService.SignRequestType SignRequest1) {
            Sjuklöner.BankIDService.SignRequest inValue = new Sjuklöner.BankIDService.SignRequest();
            inValue.SignRequest1 = SignRequest1;
            return ((Sjuklöner.BankIDService.RpServicePortType)(this)).SignAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sjuklöner.BankIDService.FileSignResponse Sjuklöner.BankIDService.RpServicePortType.FileSign(Sjuklöner.BankIDService.FileSignRequest request) {
            return base.Channel.FileSign(request);
        }
        
        public Sjuklöner.BankIDService.OrderResponseType FileSign(Sjuklöner.BankIDService.FileSignRequestType FileSignRequest1) {
            Sjuklöner.BankIDService.FileSignRequest inValue = new Sjuklöner.BankIDService.FileSignRequest();
            inValue.FileSignRequest1 = FileSignRequest1;
            Sjuklöner.BankIDService.FileSignResponse retVal = ((Sjuklöner.BankIDService.RpServicePortType)(this)).FileSign(inValue);
            return retVal.FileSignResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Sjuklöner.BankIDService.FileSignResponse> Sjuklöner.BankIDService.RpServicePortType.FileSignAsync(Sjuklöner.BankIDService.FileSignRequest request) {
            return base.Channel.FileSignAsync(request);
        }
        
        public System.Threading.Tasks.Task<Sjuklöner.BankIDService.FileSignResponse> FileSignAsync(Sjuklöner.BankIDService.FileSignRequestType FileSignRequest1) {
            Sjuklöner.BankIDService.FileSignRequest inValue = new Sjuklöner.BankIDService.FileSignRequest();
            inValue.FileSignRequest1 = FileSignRequest1;
            return ((Sjuklöner.BankIDService.RpServicePortType)(this)).FileSignAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sjuklöner.BankIDService.CollectResponse Sjuklöner.BankIDService.RpServicePortType.Collect(Sjuklöner.BankIDService.CollectRequest request) {
            return base.Channel.Collect(request);
        }
        
        public Sjuklöner.BankIDService.CollectResponseType Collect(string orderRef) {
            Sjuklöner.BankIDService.CollectRequest inValue = new Sjuklöner.BankIDService.CollectRequest();
            inValue.orderRef = orderRef;
            Sjuklöner.BankIDService.CollectResponse retVal = ((Sjuklöner.BankIDService.RpServicePortType)(this)).Collect(inValue);
            return retVal.CollectResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Sjuklöner.BankIDService.CollectResponse> Sjuklöner.BankIDService.RpServicePortType.CollectAsync(Sjuklöner.BankIDService.CollectRequest request) {
            return base.Channel.CollectAsync(request);
        }
        
        public System.Threading.Tasks.Task<Sjuklöner.BankIDService.CollectResponse> CollectAsync(string orderRef) {
            Sjuklöner.BankIDService.CollectRequest inValue = new Sjuklöner.BankIDService.CollectRequest();
            inValue.orderRef = orderRef;
            return ((Sjuklöner.BankIDService.RpServicePortType)(this)).CollectAsync(inValue);
        }
    }
}
