namespace Sjuklöner.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class _new : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Messages", "applicationUser_Id", "dbo.AspNetUsers");
            DropIndex("dbo.Messages", new[] { "applicationUser_Id" });
            AddColumn("dbo.Claims", "SickPay", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Claims", "HolidayPay", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Claims", "SocialFees", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Claims", "PensionAndInsurance", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Claims", "ClaimSum", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Messages", "ApplicationUser_Id1", c => c.String(maxLength: 128));
            AlterColumn("dbo.Messages", "ApplicationUser_Id", c => c.String());
            CreateIndex("dbo.Messages", "ApplicationUser_Id1");
            AddForeignKey("dbo.Messages", "ApplicationUser_Id1", "dbo.AspNetUsers", "Id");
            DropColumn("dbo.Claims", "ClaimedSickPay");
            DropColumn("dbo.Claims", "ClaimedHolidayPay");
            DropColumn("dbo.Claims", "ClaimedSocialFees");
            DropColumn("dbo.Claims", "ClaimedPensionAndInsurance");
            DropColumn("dbo.Claims", "ClaimedSum");
            DropColumn("dbo.Claims", "SickPayRate");
            DropColumn("dbo.Claims", "HolidayPayRate");
            DropColumn("dbo.Claims", "SocialFeeRate");
            DropColumn("dbo.Claims", "PensionAndInsuranceRate");
            DropColumn("dbo.Claims", "HourlySalary");
            DropColumn("dbo.Claims", "PerHourUnsocialEvening");
            DropColumn("dbo.Claims", "PerHourUnsocialNight");
            DropColumn("dbo.Claims", "PerHourUnsocialWeekend");
            DropColumn("dbo.Claims", "PerHourUnsocialHoliday");
            DropColumn("dbo.Claims", "PerHourOnCallWeekday");
            DropColumn("dbo.Claims", "PerHourOnCallWeekend");
            DropColumn("dbo.Claims", "HourlySalaryAsString");
            DropColumn("dbo.Claims", "SickPayRateAsString");
            DropColumn("dbo.Claims", "HolidayPayRateAsString");
            DropColumn("dbo.Claims", "SocialFeeRateAsString");
            DropColumn("dbo.Claims", "PensionAndInsuranceRateAsString");
            DropColumn("dbo.Claims", "PerHourUnsocialEveningAsString");
            DropColumn("dbo.Claims", "PerHourUnsocialNightAsString");
            DropColumn("dbo.Claims", "PerHourUnsocialWeekendAsString");
            DropColumn("dbo.Claims", "PerHourUnsocialHolidayAsString");
            DropColumn("dbo.Claims", "PerHourOnCallDayAsString");
            DropColumn("dbo.Claims", "PerHourOnCallNightAsString");
            DropColumn("dbo.Claims", "HoursQD");
            DropColumn("dbo.Claims", "HolidayPayQD");
            DropColumn("dbo.Claims", "HolidayPayCalcQD");
            DropColumn("dbo.Claims", "SocialFeesQD");
            DropColumn("dbo.Claims", "SocialFeesCalcQD");
            DropColumn("dbo.Claims", "PensionAndInsuranceQD");
            DropColumn("dbo.Claims", "PensionAndInsuranceCalcQD");
            DropColumn("dbo.Claims", "CostQD");
            DropColumn("dbo.Claims", "CostCalcQD");
            DropColumn("dbo.Claims", "HoursD2T14");
            DropColumn("dbo.Claims", "SalaryD2T14");
            DropColumn("dbo.Claims", "SalaryCalcD2T14");
            DropColumn("dbo.Claims", "SickPayD2T14");
            DropColumn("dbo.Claims", "SickPayCalcD2T14");
            DropColumn("dbo.Claims", "HolidayPayD2T14");
            DropColumn("dbo.Claims", "HolidayPayCalcD2T14");
            DropColumn("dbo.Claims", "UnsocialEveningD2T14");
            DropColumn("dbo.Claims", "UnsocialEveningPayD2T14");
            DropColumn("dbo.Claims", "UnsocialEveningPayCalcD2T14");
            DropColumn("dbo.Claims", "UnsocialNightD2T14");
            DropColumn("dbo.Claims", "UnsocialNightPayD2T14");
            DropColumn("dbo.Claims", "UnsocialNightPayCalcD2T14");
            DropColumn("dbo.Claims", "UnsocialWeekendD2T14");
            DropColumn("dbo.Claims", "UnsocialWeekendPayD2T14");
            DropColumn("dbo.Claims", "UnsocialWeekendPayCalcD2T14");
            DropColumn("dbo.Claims", "UnsocialGrandWeekendD2T14");
            DropColumn("dbo.Claims", "UnsocialGrandWeekendPayD2T14");
            DropColumn("dbo.Claims", "UnsocialGrandWeekendPayCalcD2T14");
            DropColumn("dbo.Claims", "UnsocialSumD2T14");
            DropColumn("dbo.Claims", "UnsocialSumPayD2T14");
            DropColumn("dbo.Claims", "UnsocialSumPayCalcD2T14");
            DropColumn("dbo.Claims", "OnCallDayD2T14");
            DropColumn("dbo.Claims", "OnCallDayPayD2T14");
            DropColumn("dbo.Claims", "OnCallDayPayCalcD2T14");
            DropColumn("dbo.Claims", "OnCallNightD2T14");
            DropColumn("dbo.Claims", "OnCallNightPayD2T14");
            DropColumn("dbo.Claims", "OnCallNightPayCalcD2T14");
            DropColumn("dbo.Claims", "OnCallSumD2T14");
            DropColumn("dbo.Claims", "OnCallSumPayD2T14");
            DropColumn("dbo.Claims", "OnCallSumPayCalcD2T14");
            DropColumn("dbo.Claims", "SocialFeesD2T14");
            DropColumn("dbo.Claims", "SocialFeesCalcD2T14");
            DropColumn("dbo.Claims", "PensionAndInsuranceD2T14");
            DropColumn("dbo.Claims", "PensionAndInsuranceCalcD2T14");
            DropColumn("dbo.Claims", "CostD2T14");
            DropColumn("dbo.Claims", "CostCalcD2T14");
            DropColumn("dbo.Claims", "TotalCostD1T14");
            DropColumn("dbo.Claims", "TotalCostCalcD1T14");
        }
        
        public override void Down()
        {
            AddColumn("dbo.Claims", "TotalCostCalcD1T14", c => c.String());
            AddColumn("dbo.Claims", "TotalCostD1T14", c => c.String());
            AddColumn("dbo.Claims", "CostCalcD2T14", c => c.String());
            AddColumn("dbo.Claims", "CostD2T14", c => c.String());
            AddColumn("dbo.Claims", "PensionAndInsuranceCalcD2T14", c => c.String());
            AddColumn("dbo.Claims", "PensionAndInsuranceD2T14", c => c.String());
            AddColumn("dbo.Claims", "SocialFeesCalcD2T14", c => c.String());
            AddColumn("dbo.Claims", "SocialFeesD2T14", c => c.String());
            AddColumn("dbo.Claims", "OnCallSumPayCalcD2T14", c => c.String());
            AddColumn("dbo.Claims", "OnCallSumPayD2T14", c => c.String());
            AddColumn("dbo.Claims", "OnCallSumD2T14", c => c.String());
            AddColumn("dbo.Claims", "OnCallNightPayCalcD2T14", c => c.String());
            AddColumn("dbo.Claims", "OnCallNightPayD2T14", c => c.String());
            AddColumn("dbo.Claims", "OnCallNightD2T14", c => c.String());
            AddColumn("dbo.Claims", "OnCallDayPayCalcD2T14", c => c.String());
            AddColumn("dbo.Claims", "OnCallDayPayD2T14", c => c.String());
            AddColumn("dbo.Claims", "OnCallDayD2T14", c => c.String());
            AddColumn("dbo.Claims", "UnsocialSumPayCalcD2T14", c => c.String());
            AddColumn("dbo.Claims", "UnsocialSumPayD2T14", c => c.String());
            AddColumn("dbo.Claims", "UnsocialSumD2T14", c => c.String());
            AddColumn("dbo.Claims", "UnsocialGrandWeekendPayCalcD2T14", c => c.String());
            AddColumn("dbo.Claims", "UnsocialGrandWeekendPayD2T14", c => c.String());
            AddColumn("dbo.Claims", "UnsocialGrandWeekendD2T14", c => c.String());
            AddColumn("dbo.Claims", "UnsocialWeekendPayCalcD2T14", c => c.String());
            AddColumn("dbo.Claims", "UnsocialWeekendPayD2T14", c => c.String());
            AddColumn("dbo.Claims", "UnsocialWeekendD2T14", c => c.String());
            AddColumn("dbo.Claims", "UnsocialNightPayCalcD2T14", c => c.String());
            AddColumn("dbo.Claims", "UnsocialNightPayD2T14", c => c.String());
            AddColumn("dbo.Claims", "UnsocialNightD2T14", c => c.String());
            AddColumn("dbo.Claims", "UnsocialEveningPayCalcD2T14", c => c.String());
            AddColumn("dbo.Claims", "UnsocialEveningPayD2T14", c => c.String());
            AddColumn("dbo.Claims", "UnsocialEveningD2T14", c => c.String());
            AddColumn("dbo.Claims", "HolidayPayCalcD2T14", c => c.String());
            AddColumn("dbo.Claims", "HolidayPayD2T14", c => c.String());
            AddColumn("dbo.Claims", "SickPayCalcD2T14", c => c.String());
            AddColumn("dbo.Claims", "SickPayD2T14", c => c.String());
            AddColumn("dbo.Claims", "SalaryCalcD2T14", c => c.String());
            AddColumn("dbo.Claims", "SalaryD2T14", c => c.String());
            AddColumn("dbo.Claims", "HoursD2T14", c => c.String());
            AddColumn("dbo.Claims", "CostCalcQD", c => c.String());
            AddColumn("dbo.Claims", "CostQD", c => c.String());
            AddColumn("dbo.Claims", "PensionAndInsuranceCalcQD", c => c.String());
            AddColumn("dbo.Claims", "PensionAndInsuranceQD", c => c.String());
            AddColumn("dbo.Claims", "SocialFeesCalcQD", c => c.String());
            AddColumn("dbo.Claims", "SocialFeesQD", c => c.String());
            AddColumn("dbo.Claims", "HolidayPayCalcQD", c => c.String());
            AddColumn("dbo.Claims", "HolidayPayQD", c => c.String());
            AddColumn("dbo.Claims", "HoursQD", c => c.String());
            AddColumn("dbo.Claims", "PerHourOnCallNightAsString", c => c.String());
            AddColumn("dbo.Claims", "PerHourOnCallDayAsString", c => c.String());
            AddColumn("dbo.Claims", "PerHourUnsocialHolidayAsString", c => c.String());
            AddColumn("dbo.Claims", "PerHourUnsocialWeekendAsString", c => c.String());
            AddColumn("dbo.Claims", "PerHourUnsocialNightAsString", c => c.String());
            AddColumn("dbo.Claims", "PerHourUnsocialEveningAsString", c => c.String());
            AddColumn("dbo.Claims", "PensionAndInsuranceRateAsString", c => c.String());
            AddColumn("dbo.Claims", "SocialFeeRateAsString", c => c.String());
            AddColumn("dbo.Claims", "HolidayPayRateAsString", c => c.String());
            AddColumn("dbo.Claims", "SickPayRateAsString", c => c.String());
            AddColumn("dbo.Claims", "HourlySalaryAsString", c => c.String());
            AddColumn("dbo.Claims", "PerHourOnCallWeekend", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Claims", "PerHourOnCallWeekday", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Claims", "PerHourUnsocialHoliday", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Claims", "PerHourUnsocialWeekend", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Claims", "PerHourUnsocialNight", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Claims", "PerHourUnsocialEvening", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Claims", "HourlySalary", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Claims", "PensionAndInsuranceRate", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Claims", "SocialFeeRate", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Claims", "HolidayPayRate", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Claims", "SickPayRate", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Claims", "ClaimedSum", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Claims", "ClaimedPensionAndInsurance", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Claims", "ClaimedSocialFees", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Claims", "ClaimedHolidayPay", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Claims", "ClaimedSickPay", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            DropForeignKey("dbo.Messages", "ApplicationUser_Id1", "dbo.AspNetUsers");
            DropIndex("dbo.Messages", new[] { "ApplicationUser_Id1" });
            AlterColumn("dbo.Messages", "ApplicationUser_Id", c => c.String(maxLength: 128));
            DropColumn("dbo.Messages", "ApplicationUser_Id1");
            DropColumn("dbo.Claims", "ClaimSum");
            DropColumn("dbo.Claims", "PensionAndInsurance");
            DropColumn("dbo.Claims", "SocialFees");
            DropColumn("dbo.Claims", "HolidayPay");
            DropColumn("dbo.Claims", "SickPay");
            CreateIndex("dbo.Messages", "applicationUser_Id");
            AddForeignKey("dbo.Messages", "applicationUser_Id", "dbo.AspNetUsers", "Id");
        }
    }
}
