// <auto-generated />
namespace Sjuklöner.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _201805160538192_AddedNumberOfSubAssistantPropertyToClaimClass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201805160538192_AddedNumberOfSubAssistantPropertyToClaimClass));
        
        string IMigrationMetadata.Id
        {
            get { return "201805231343076_201805160538192_AddedNumberOfSubAssistantPropertyToClaimClass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
